version: "3.8"
services:
    app_name_db:
        image: postgres:15.4-alpine
        container_name: app_name-database
        env_file: ./.env
        volumes:
            - dbdata:/var/lib/app_name-database/data
        ports:
            - 5432:5432
    api:
        depends_on:
            - app_name_db
        entrypoint: [ "/bin/sh", "./wait_for_db.sh" ]
        ports:
            - $PORT:$PORT
