"""empty message

Revision ID: a71669a129c0
Revises: 43ac8b2e9de4
Create Date: 2024-07-21 09:32:23.861568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71669a129c0'
down_revision = '43ac8b2e9de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chicken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('color', sa.Enum('ALICE_BLUE', 'ANTIQUEWHITE', 'AQUA', 'AQUAMARINE', 'AZURE', 'BEIGE', 'BISQUE', 'BLACK', 'BLANCHED_ALMOND', 'BLUE', 'BLUE_VIOLET', 'BROWN', 'BURLYWOOD', 'CADET_BLUE', 'CHARTREUSE', 'CHOCOLATE', 'CORAL', 'CORNFLOWER_BLUE', 'CORNSILK', 'CRIMSON', 'DARK_BLUE', 'DARK_CYAN', 'DARK_GOLDEN_ROD', 'DARK_GRAY', 'DARK_GREEN', 'DARK_KHAKI', 'DARK_MAGENTA', 'DARK_OLIVE_GREEN', 'DARK_ORANGE', 'DARK_ORCHID', 'DARK_RED', 'DARK_SALMON', 'DARK_SEA_GREEN', 'DARK_SLATE_BLUE', 'DARK_SLATE_GRAY', 'DARK_TURQUOISE', 'DARK_VIOLET', 'DEEP_PINK', 'DEEP_SKY_BLUE', 'DIM_GRAY', 'DODGER_BLUE', 'FIRE_BRICK', 'FLORALWHITE', 'FOREST_GREEN', 'FUCHSIA', 'GAINSBORO', 'GHOSTWHITE', 'GOLD', 'GOLDEN_ROD', 'GRAY', 'GREEN', 'GREEN_YELLOW', 'HONEY_DEW', 'HOT_PINK', 'INDIAN_RED', 'INDIGO', 'IVORY', 'KHAKI', 'LAVENDER', 'LAVENDER_BLUSH', 'LAWN_GREEN', 'LEMON_CHIFFON', 'LIGHT_BLUE', 'LIGHT_CORAL', 'LIGHT_CYAN', 'LIGHT_GOLDEN_ROD_YELLOW', 'LIGHT_GRAY', 'LIGHT_GREEN', 'LIGHT_PINK', 'LIGHT_SALMON', 'LIGHT_SEA_GREEN', 'LIGHT_SKY_BLUE', 'LIGHT_SLATE_GRAY', 'LIGHT_STEEL_BLUE', 'LIGHT_YELLOW', 'LIME', 'LIME_GREEN', 'LINEN', 'MAROON', 'MEDIUM_AQUA_MARINE', 'MEDIUM_BLUE', 'MEDIUM_ORCHID', 'MEDIUM_PURPLE', 'MEDIUM_SEA_GREEN', 'MEDIUM_SLATE_BLUE', 'MEDIUM_SPRING_GREEN', 'MEDIUM_TURQUOISE', 'MEDIUM_VIOLET_RED', 'MIDNIGHT_BLUE', 'MINT_CREAM', 'MISTY_ROSE', 'MOCCASIN', 'NAVAJOWHITE', 'NAVY', 'OLD_LACE', 'OLIVE', 'OLIVE_DRAB', 'ORANGE', 'ORANGE_RED', 'ORCHID', 'PALE_GOLDEN_ROD', 'PALE_GREEN', 'PALE_TURQUOISE', 'PALE_VIOLET_RED', 'PAPAYAWHIP', 'PEACH_PUFF', 'PERU', 'PINK', 'PLUM', 'POWDER_BLUE', 'PURPLE', 'REBECCA_PURPLE', 'RED', 'ROSY_BROWN', 'ROYAL_BLUE', 'SADDLE_BROWN', 'SALMON', 'SANDY_BROWN', 'SEA_GREEN', 'SEA_SHELL', 'SIENNA', 'SILVER', 'SKY_BLUE', 'SLATE_BLUE', 'SLATE_GRAY', 'SNOW', 'SPRING_GREEN', 'STEEL_BLUE', 'TAN', 'TEAL', 'THISTLE', 'TOMATO', 'TURQUOISE', 'VIOLET', 'WHEAT', 'WHITE', 'WHITE_SMOKE', 'YELLOW', 'YELLOW_GREEN', name='csscolor'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('chicken_trait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chicken_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('trait', sa.Enum('COWARDLY', 'BRAVE', 'SMART', 'HAPPY', 'SAD', 'FUNNY', 'LAZY', 'EMOTIONAL', 'LONELY', name='personalitytrait'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chicken_id'], ['chicken.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chicken_trait')
    op.drop_table('chicken')
    # ### end Alembic commands ###
